# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

struct AppsPermissionsScopesApi <: SwaggerApi
    client::Swagger.Client
end

function _swaggerinternal_appsPermissionsScopesList(_api::AppsPermissionsScopesApi; _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "GET", Dict{String, Any}, "/apps.permissions.scopes.list", ["slackAuth"])
    Swagger.set_header_accept(_ctx, ["application/json"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/x-www-form-urlencoded"] : [_mediaType])
    return _ctx
end

"""

Returns list of scopes this app has on a team.
Return: Dict{String, Any}
"""
function appsPermissionsScopesList(_api::AppsPermissionsScopesApi; _mediaType=nothing)
    _ctx = _swaggerinternal_appsPermissionsScopesList(_api; _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function appsPermissionsScopesList(_api::AppsPermissionsScopesApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _swaggerinternal_appsPermissionsScopesList(_api; _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

export appsPermissionsScopesList
