# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

struct FilesCommentsApi <: SwaggerApi
    client::Swagger.Client
end

function _swaggerinternal_filesCommentsDelete(_api::FilesCommentsApi; file=nothing, id=nothing, _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "POST", Dict{String, Any}, "/files.comments.delete", ["slackAuth"])
    Swagger.set_param(_ctx.form, "file", file)  # type String
    Swagger.set_param(_ctx.form, "id", id)  # type String
    Swagger.set_header_accept(_ctx, ["application/json"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/x-www-form-urlencoded", "application/json"] : [_mediaType])
    return _ctx
end

"""

Deletes an existing comment on a file.
Param: file::String
Param: id::String
Return: Dict{String, Any}
"""
function filesCommentsDelete(_api::FilesCommentsApi; file=nothing, id=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_filesCommentsDelete(_api; file=file, id=id, _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function filesCommentsDelete(_api::FilesCommentsApi, response_stream::Channel; file=nothing, id=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_filesCommentsDelete(_api; file=file, id=id, _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

export filesCommentsDelete
