# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

struct ChatScheduledMessagesApi <: SwaggerApi
    client::Swagger.Client
end

function _swaggerinternal_chatScheduledMessagesList(_api::ChatScheduledMessagesApi; channel=nothing, latest=nothing, oldest=nothing, limit=nothing, cursor=nothing, _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "GET", Dict{String, Any}, "/chat.scheduledMessages.list", ["slackAuth"])
    Swagger.set_param(_ctx.query, "channel", channel)  # type String
    Swagger.set_param(_ctx.query, "latest", latest)  # type Float32
    Swagger.set_param(_ctx.query, "oldest", oldest)  # type Float32
    Swagger.set_param(_ctx.query, "limit", limit)  # type Int32
    Swagger.set_param(_ctx.query, "cursor", cursor)  # type String
    Swagger.set_header_accept(_ctx, ["application/json"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/x-www-form-urlencoded", "application/json"] : [_mediaType])
    return _ctx
end

"""

Returns a list of scheduled messages.
Param: channel::String
Param: latest::Float32
Param: oldest::Float32
Param: limit::Int32
Param: cursor::String
Return: Dict{String, Any}
"""
function chatScheduledMessagesList(_api::ChatScheduledMessagesApi; channel=nothing, latest=nothing, oldest=nothing, limit=nothing, cursor=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_chatScheduledMessagesList(_api; channel=channel, latest=latest, oldest=oldest, limit=limit, cursor=cursor, _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function chatScheduledMessagesList(_api::ChatScheduledMessagesApi, response_stream::Channel; channel=nothing, latest=nothing, oldest=nothing, limit=nothing, cursor=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_chatScheduledMessagesList(_api; channel=channel, latest=latest, oldest=oldest, limit=limit, cursor=cursor, _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

export chatScheduledMessagesList
