# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

struct AppsPermissionsResourcesApi <: SwaggerApi
    client::Swagger.Client
end

function _swaggerinternal_appsPermissionsResourcesList(_api::AppsPermissionsResourcesApi; cursor=nothing, limit=nothing, _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "GET", Dict{String, Any}, "/apps.permissions.resources.list", ["slackAuth"])
    Swagger.set_param(_ctx.query, "cursor", cursor)  # type String
    Swagger.set_param(_ctx.query, "limit", limit)  # type Int32
    Swagger.set_header_accept(_ctx, ["application/json"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/x-www-form-urlencoded"] : [_mediaType])
    return _ctx
end

"""

Returns list of resource grants this app has on a team.
Param: cursor::String
Param: limit::Int32
Return: Dict{String, Any}
"""
function appsPermissionsResourcesList(_api::AppsPermissionsResourcesApi; cursor=nothing, limit=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_appsPermissionsResourcesList(_api; cursor=cursor, limit=limit, _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function appsPermissionsResourcesList(_api::AppsPermissionsResourcesApi, response_stream::Channel; cursor=nothing, limit=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_appsPermissionsResourcesList(_api; cursor=cursor, limit=limit, _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

export appsPermissionsResourcesList
