# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

struct ApiApi <: SwaggerApi
    client::Swagger.Client
end

function _swaggerinternal_apiTest(_api::ApiApi; error=nothing, foo=nothing, _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "GET", Dict{String, Any}, "/api.test", ["slackAuth"])
    Swagger.set_param(_ctx.query, "error", error)  # type String
    Swagger.set_param(_ctx.query, "foo", foo)  # type String
    Swagger.set_header_accept(_ctx, ["application/json"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/x-www-form-urlencoded", "application/json"] : [_mediaType])
    return _ctx
end

"""

Checks API calling code.
Param: error::String
Param: foo::String
Return: Dict{String, Any}
"""
function apiTest(_api::ApiApi; error=nothing, foo=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_apiTest(_api; error=error, foo=foo, _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function apiTest(_api::ApiApi, response_stream::Channel; error=nothing, foo=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_apiTest(_api; error=error, foo=foo, _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

export apiTest
