# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

struct AuthApi <: SwaggerApi
    client::Swagger.Client
end

function _swaggerinternal_authRevoke(_api::AuthApi; test=nothing, _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "GET", Dict{String, Any}, "/auth.revoke", ["slackAuth"])
    Swagger.set_param(_ctx.query, "test", test)  # type Bool
    Swagger.set_header_accept(_ctx, ["application/json"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/x-www-form-urlencoded"] : [_mediaType])
    return _ctx
end

"""

Revokes a token.
Param: test::Bool
Return: Dict{String, Any}
"""
function authRevoke(_api::AuthApi; test=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_authRevoke(_api; test=test, _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function authRevoke(_api::AuthApi, response_stream::Channel; test=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_authRevoke(_api; test=test, _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

function _swaggerinternal_authTest(_api::AuthApi; _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "GET", Dict{String, Any}, "/auth.test", ["slackAuth"])
    Swagger.set_header_accept(_ctx, ["application/json"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/x-www-form-urlencoded", "application/json"] : [_mediaType])
    return _ctx
end

"""

Checks authentication & identity.
Return: Dict{String, Any}
"""
function authTest(_api::AuthApi; _mediaType=nothing)
    _ctx = _swaggerinternal_authTest(_api; _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function authTest(_api::AuthApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _swaggerinternal_authTest(_api; _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

export authRevoke, authTest
