# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

struct TeamProfileApi <: SwaggerApi
    client::Swagger.Client
end

function _swaggerinternal_teamProfileGet(_api::TeamProfileApi; visibility=nothing, _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "GET", Dict{String, Any}, "/team.profile.get", ["slackAuth"])
    Swagger.set_param(_ctx.query, "visibility", visibility)  # type String
    Swagger.set_header_accept(_ctx, ["application/json"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/x-www-form-urlencoded"] : [_mediaType])
    return _ctx
end

"""

Retrieve a team's profile.
Param: visibility::String
Return: Dict{String, Any}
"""
function teamProfileGet(_api::TeamProfileApi; visibility=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_teamProfileGet(_api; visibility=visibility, _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function teamProfileGet(_api::TeamProfileApi, response_stream::Channel; visibility=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_teamProfileGet(_api; visibility=visibility, _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

export teamProfileGet
