# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

struct EmojiApi <: SwaggerApi
    client::Swagger.Client
end

function _swaggerinternal_emojiList(_api::EmojiApi; _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "GET", Dict{String, Any}, "/emoji.list", ["slackAuth"])
    Swagger.set_header_accept(_ctx, ["application/json"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/x-www-form-urlencoded"] : [_mediaType])
    return _ctx
end

"""

Lists custom emoji for a team.
Return: Dict{String, Any}
"""
function emojiList(_api::EmojiApi; _mediaType=nothing)
    _ctx = _swaggerinternal_emojiList(_api; _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function emojiList(_api::EmojiApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _swaggerinternal_emojiList(_api; _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

export emojiList
