# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

struct RtmApi <: SwaggerApi
    client::Swagger.Client
end

function _swaggerinternal_rtmConnect(_api::RtmApi; batch_presence_aware=nothing, presence_sub=nothing, _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "GET", Dict{String, Any}, "/rtm.connect", ["slackAuth"])
    Swagger.set_param(_ctx.query, "batch_presence_aware", batch_presence_aware)  # type Bool
    Swagger.set_param(_ctx.query, "presence_sub", presence_sub)  # type Bool
    Swagger.set_header_accept(_ctx, ["application/json"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/x-www-form-urlencoded"] : [_mediaType])
    return _ctx
end

"""

Starts a Real Time Messaging session.
Param: batch_presence_aware::Bool
Param: presence_sub::Bool
Return: Dict{String, Any}
"""
function rtmConnect(_api::RtmApi; batch_presence_aware=nothing, presence_sub=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_rtmConnect(_api; batch_presence_aware=batch_presence_aware, presence_sub=presence_sub, _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function rtmConnect(_api::RtmApi, response_stream::Channel; batch_presence_aware=nothing, presence_sub=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_rtmConnect(_api; batch_presence_aware=batch_presence_aware, presence_sub=presence_sub, _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

export rtmConnect
