# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

if !isdefined(@__MODULE__, :DefsChannelId)
    const DefsChannelId = String
else
    @warn("Skipping redefinition of DefsChannelId to String")
end

