# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""
    ObjsExternalOrgMigrationsCurrent(;
        date_started=nothing,
        team_id=nothing,
    )

    - date_started::Int32
    - team_id::String
"""
mutable struct ObjsExternalOrgMigrationsCurrent <: SwaggerModel
    date_started::Any # spec type: Union{ Nothing, Int32 } # spec name: date_started
    team_id::Any # spec type: Union{ Nothing, String } # spec name: team_id

    function ObjsExternalOrgMigrationsCurrent(;date_started=nothing, team_id=nothing)
        o = new()
        validate_property(ObjsExternalOrgMigrationsCurrent, Symbol("date_started"), date_started)
        setfield!(o, Symbol("date_started"), date_started)
        validate_property(ObjsExternalOrgMigrationsCurrent, Symbol("team_id"), team_id)
        setfield!(o, Symbol("team_id"), team_id)
        o
    end
end # type ObjsExternalOrgMigrationsCurrent

const _property_map_ObjsExternalOrgMigrationsCurrent = Dict{Symbol,Symbol}(Symbol("date_started")=>Symbol("date_started"), Symbol("team_id")=>Symbol("team_id"))
const _property_types_ObjsExternalOrgMigrationsCurrent = Dict{Symbol,String}(Symbol("date_started")=>"Int32", Symbol("team_id")=>"String")
Base.propertynames(::Type{ ObjsExternalOrgMigrationsCurrent }) = collect(keys(_property_map_ObjsExternalOrgMigrationsCurrent))
Swagger.property_type(::Type{ ObjsExternalOrgMigrationsCurrent }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ObjsExternalOrgMigrationsCurrent[name]))}
Swagger.field_name(::Type{ ObjsExternalOrgMigrationsCurrent }, property_name::Symbol) =  _property_map_ObjsExternalOrgMigrationsCurrent[property_name]

function check_required(o::ObjsExternalOrgMigrationsCurrent)
    (getproperty(o, Symbol("date_started")) === nothing) && (return false)
    (getproperty(o, Symbol("team_id")) === nothing) && (return false)
    true
end

function validate_property(::Type{ ObjsExternalOrgMigrationsCurrent }, name::Symbol, val)
end
