# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""
    ObjsIcon(;
        image_102=nothing,
        image_132=nothing,
        image_230=nothing,
        image_34=nothing,
        image_44=nothing,
        image_68=nothing,
        image_88=nothing,
        image_default=nothing,
    )

    - image_102::String
    - image_132::String
    - image_230::String
    - image_34::String
    - image_44::String
    - image_68::String
    - image_88::String
    - image_default::Bool
"""
mutable struct ObjsIcon <: SwaggerModel
    image_102::Any # spec type: Union{ Nothing, String } # spec name: image_102
    image_132::Any # spec type: Union{ Nothing, String } # spec name: image_132
    image_230::Any # spec type: Union{ Nothing, String } # spec name: image_230
    image_34::Any # spec type: Union{ Nothing, String } # spec name: image_34
    image_44::Any # spec type: Union{ Nothing, String } # spec name: image_44
    image_68::Any # spec type: Union{ Nothing, String } # spec name: image_68
    image_88::Any # spec type: Union{ Nothing, String } # spec name: image_88
    image_default::Any # spec type: Union{ Nothing, Bool } # spec name: image_default

    function ObjsIcon(;image_102=nothing, image_132=nothing, image_230=nothing, image_34=nothing, image_44=nothing, image_68=nothing, image_88=nothing, image_default=nothing)
        o = new()
        validate_property(ObjsIcon, Symbol("image_102"), image_102)
        setfield!(o, Symbol("image_102"), image_102)
        validate_property(ObjsIcon, Symbol("image_132"), image_132)
        setfield!(o, Symbol("image_132"), image_132)
        validate_property(ObjsIcon, Symbol("image_230"), image_230)
        setfield!(o, Symbol("image_230"), image_230)
        validate_property(ObjsIcon, Symbol("image_34"), image_34)
        setfield!(o, Symbol("image_34"), image_34)
        validate_property(ObjsIcon, Symbol("image_44"), image_44)
        setfield!(o, Symbol("image_44"), image_44)
        validate_property(ObjsIcon, Symbol("image_68"), image_68)
        setfield!(o, Symbol("image_68"), image_68)
        validate_property(ObjsIcon, Symbol("image_88"), image_88)
        setfield!(o, Symbol("image_88"), image_88)
        validate_property(ObjsIcon, Symbol("image_default"), image_default)
        setfield!(o, Symbol("image_default"), image_default)
        o
    end
end # type ObjsIcon

const _property_map_ObjsIcon = Dict{Symbol,Symbol}(Symbol("image_102")=>Symbol("image_102"), Symbol("image_132")=>Symbol("image_132"), Symbol("image_230")=>Symbol("image_230"), Symbol("image_34")=>Symbol("image_34"), Symbol("image_44")=>Symbol("image_44"), Symbol("image_68")=>Symbol("image_68"), Symbol("image_88")=>Symbol("image_88"), Symbol("image_default")=>Symbol("image_default"))
const _property_types_ObjsIcon = Dict{Symbol,String}(Symbol("image_102")=>"String", Symbol("image_132")=>"String", Symbol("image_230")=>"String", Symbol("image_34")=>"String", Symbol("image_44")=>"String", Symbol("image_68")=>"String", Symbol("image_88")=>"String", Symbol("image_default")=>"Bool")
Base.propertynames(::Type{ ObjsIcon }) = collect(keys(_property_map_ObjsIcon))
Swagger.property_type(::Type{ ObjsIcon }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ObjsIcon[name]))}
Swagger.field_name(::Type{ ObjsIcon }, property_name::Symbol) =  _property_map_ObjsIcon[property_name]

function check_required(o::ObjsIcon)
    true
end

function validate_property(::Type{ ObjsIcon }, name::Symbol, val)
end
