# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

if !isdefined(@__MODULE__, :DefsBotId)
    const DefsBotId = String
else
    @warn("Skipping redefinition of DefsBotId to String")
end

