# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""
    ObjsBotProfileIcons(;
        image_36=nothing,
        image_48=nothing,
        image_72=nothing,
    )

    - image_36::String
    - image_48::String
    - image_72::String
"""
mutable struct ObjsBotProfileIcons <: SwaggerModel
    image_36::Any # spec type: Union{ Nothing, String } # spec name: image_36
    image_48::Any # spec type: Union{ Nothing, String } # spec name: image_48
    image_72::Any # spec type: Union{ Nothing, String } # spec name: image_72

    function ObjsBotProfileIcons(;image_36=nothing, image_48=nothing, image_72=nothing)
        o = new()
        validate_property(ObjsBotProfileIcons, Symbol("image_36"), image_36)
        setfield!(o, Symbol("image_36"), image_36)
        validate_property(ObjsBotProfileIcons, Symbol("image_48"), image_48)
        setfield!(o, Symbol("image_48"), image_48)
        validate_property(ObjsBotProfileIcons, Symbol("image_72"), image_72)
        setfield!(o, Symbol("image_72"), image_72)
        o
    end
end # type ObjsBotProfileIcons

const _property_map_ObjsBotProfileIcons = Dict{Symbol,Symbol}(Symbol("image_36")=>Symbol("image_36"), Symbol("image_48")=>Symbol("image_48"), Symbol("image_72")=>Symbol("image_72"))
const _property_types_ObjsBotProfileIcons = Dict{Symbol,String}(Symbol("image_36")=>"String", Symbol("image_48")=>"String", Symbol("image_72")=>"String")
Base.propertynames(::Type{ ObjsBotProfileIcons }) = collect(keys(_property_map_ObjsBotProfileIcons))
Swagger.property_type(::Type{ ObjsBotProfileIcons }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ObjsBotProfileIcons[name]))}
Swagger.field_name(::Type{ ObjsBotProfileIcons }, property_name::Symbol) =  _property_map_ObjsBotProfileIcons[property_name]

function check_required(o::ObjsBotProfileIcons)
    (getproperty(o, Symbol("image_36")) === nothing) && (return false)
    (getproperty(o, Symbol("image_48")) === nothing) && (return false)
    (getproperty(o, Symbol("image_72")) === nothing) && (return false)
    true
end

function validate_property(::Type{ ObjsBotProfileIcons }, name::Symbol, val)
end
