# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""
    DefsPinnedInfo(;
    )

"""
mutable struct DefsPinnedInfo <: SwaggerModel

    function DefsPinnedInfo(;)
        o = new()
        o
    end
end # type DefsPinnedInfo

const _property_map_DefsPinnedInfo = Dict{Symbol,Symbol}()
const _property_types_DefsPinnedInfo = Dict{Symbol,String}()
Base.propertynames(::Type{ DefsPinnedInfo }) = collect(keys(_property_map_DefsPinnedInfo))
Swagger.property_type(::Type{ DefsPinnedInfo }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DefsPinnedInfo[name]))}
Swagger.field_name(::Type{ DefsPinnedInfo }, property_name::Symbol) =  _property_map_DefsPinnedInfo[property_name]

function check_required(o::DefsPinnedInfo)
    true
end

function validate_property(::Type{ DefsPinnedInfo }, name::Symbol, val)
end
