# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""
    ObjsTeamSsoProvider(;
        label=nothing,
        name=nothing,
        type=nothing,
    )

    - label::String
    - name::String
    - type::String
"""
mutable struct ObjsTeamSsoProvider <: SwaggerModel
    label::Any # spec type: Union{ Nothing, String } # spec name: label
    name::Any # spec type: Union{ Nothing, String } # spec name: name
    type::Any # spec type: Union{ Nothing, String } # spec name: type

    function ObjsTeamSsoProvider(;label=nothing, name=nothing, type=nothing)
        o = new()
        validate_property(ObjsTeamSsoProvider, Symbol("label"), label)
        setfield!(o, Symbol("label"), label)
        validate_property(ObjsTeamSsoProvider, Symbol("name"), name)
        setfield!(o, Symbol("name"), name)
        validate_property(ObjsTeamSsoProvider, Symbol("type"), type)
        setfield!(o, Symbol("type"), type)
        o
    end
end # type ObjsTeamSsoProvider

const _property_map_ObjsTeamSsoProvider = Dict{Symbol,Symbol}(Symbol("label")=>Symbol("label"), Symbol("name")=>Symbol("name"), Symbol("type")=>Symbol("type"))
const _property_types_ObjsTeamSsoProvider = Dict{Symbol,String}(Symbol("label")=>"String", Symbol("name")=>"String", Symbol("type")=>"String")
Base.propertynames(::Type{ ObjsTeamSsoProvider }) = collect(keys(_property_map_ObjsTeamSsoProvider))
Swagger.property_type(::Type{ ObjsTeamSsoProvider }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ObjsTeamSsoProvider[name]))}
Swagger.field_name(::Type{ ObjsTeamSsoProvider }, property_name::Symbol) =  _property_map_ObjsTeamSsoProvider[property_name]

function check_required(o::ObjsTeamSsoProvider)
    true
end

function validate_property(::Type{ ObjsTeamSsoProvider }, name::Symbol, val)
end
