# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""
    ObjsScopes(;
    )

"""
mutable struct ObjsScopes <: SwaggerModel

    function ObjsScopes(;)
        o = new()
        o
    end
end # type ObjsScopes

const _property_map_ObjsScopes = Dict{Symbol,Symbol}()
const _property_types_ObjsScopes = Dict{Symbol,String}()
Base.propertynames(::Type{ ObjsScopes }) = collect(keys(_property_map_ObjsScopes))
Swagger.property_type(::Type{ ObjsScopes }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ObjsScopes[name]))}
Swagger.field_name(::Type{ ObjsScopes }, property_name::Symbol) =  _property_map_ObjsScopes[property_name]

function check_required(o::ObjsScopes)
    true
end

function validate_property(::Type{ ObjsScopes }, name::Symbol, val)
end
