# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""
    DefsOkTrue(;
    )

"""
mutable struct DefsOkTrue <: SwaggerModel

    function DefsOkTrue(;)
        o = new()
        o
    end
end # type DefsOkTrue

const _property_map_DefsOkTrue = Dict{Symbol,Symbol}()
const _property_types_DefsOkTrue = Dict{Symbol,String}()
Base.propertynames(::Type{ DefsOkTrue }) = collect(keys(_property_map_DefsOkTrue))
Swagger.property_type(::Type{ DefsOkTrue }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DefsOkTrue[name]))}
Swagger.field_name(::Type{ DefsOkTrue }, property_name::Symbol) =  _property_map_DefsOkTrue[property_name]

function check_required(o::DefsOkTrue)
    true
end

function validate_property(::Type{ DefsOkTrue }, name::Symbol, val)
end
