# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

if !isdefined(@__MODULE__, :DefsEnterpriseUserId)
    const DefsEnterpriseUserId = String
else
    @warn("Skipping redefinition of DefsEnterpriseUserId to String")
end

