# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

if !isdefined(@__MODULE__, :DefsAppId)
    const DefsAppId = String
else
    @warn("Skipping redefinition of DefsAppId to String")
end

