# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


@doc raw"""
    ObjsUser(;
    )

"""
mutable struct ObjsUser <: SwaggerModel

    function ObjsUser(;)
        o = new()
        o
    end
end # type ObjsUser

const _property_map_ObjsUser = Dict{Symbol,Symbol}()
const _property_types_ObjsUser = Dict{Symbol,String}()
Base.propertynames(::Type{ ObjsUser }) = collect(keys(_property_map_ObjsUser))
Swagger.property_type(::Type{ ObjsUser }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ObjsUser[name]))}
Swagger.field_name(::Type{ ObjsUser }, property_name::Symbol) =  _property_map_ObjsUser[property_name]

function check_required(o::ObjsUser)
    true
end

function validate_property(::Type{ ObjsUser }, name::Symbol, val)
end
