# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

module Web

using Random
using Dates
using Swagger
import Swagger: field_name, property_type, hasproperty, validate_property, SwaggerApi, SwaggerModel
import Base: convert, propertynames

include("modelincludes.jl")

include("api_AdminApi.jl")
include("api_AdminAppsApi.jl")
include("api_AdminAppsApprovedApi.jl")
include("api_AdminAppsRequestsApi.jl")
include("api_AdminAppsRestrictedApi.jl")
include("api_AdminConversationsApi.jl")
include("api_AdminConversationsEkmApi.jl")
include("api_AdminConversationsRestrictAccessApi.jl")
include("api_AdminEmojiApi.jl")
include("api_AdminInviteRequestsApi.jl")
include("api_AdminInviteRequestsApprovedApi.jl")
include("api_AdminInviteRequestsDeniedApi.jl")
include("api_AdminTeamsApi.jl")
include("api_AdminTeamsAdminsApi.jl")
include("api_AdminTeamsOwnersApi.jl")
include("api_AdminTeamsSettingsApi.jl")
include("api_AdminUsergroupsApi.jl")
include("api_AdminUsersApi.jl")
include("api_AdminUsersSessionApi.jl")
include("api_ApiApi.jl")
include("api_AppsApi.jl")
include("api_AppsEventAuthorizationsApi.jl")
include("api_AppsPermissionsApi.jl")
include("api_AppsPermissionsResourcesApi.jl")
include("api_AppsPermissionsScopesApi.jl")
include("api_AppsPermissionsUsersApi.jl")
include("api_AuthApi.jl")
include("api_BotsApi.jl")
include("api_CallsApi.jl")
include("api_CallsParticipantsApi.jl")
include("api_ChatApi.jl")
include("api_ChatScheduledMessagesApi.jl")
include("api_ConversationsApi.jl")
include("api_DialogApi.jl")
include("api_DndApi.jl")
include("api_EmojiApi.jl")
include("api_FilesApi.jl")
include("api_FilesCommentsApi.jl")
include("api_FilesRemoteApi.jl")
include("api_MigrationApi.jl")
include("api_OauthApi.jl")
include("api_OauthV2Api.jl")
include("api_PinsApi.jl")
include("api_ReactionsApi.jl")
include("api_RemindersApi.jl")
include("api_RtmApi.jl")
include("api_SearchApi.jl")
include("api_StarsApi.jl")
include("api_TeamApi.jl")
include("api_TeamProfileApi.jl")
include("api_UsergroupsApi.jl")
include("api_UsergroupsUsersApi.jl")
include("api_UsersApi.jl")
include("api_UsersProfileApi.jl")
include("api_ViewsApi.jl")
include("api_WorkflowsApi.jl")

# export models
export convert, Blocks
export convert, BlocksInner
export convert, DefsAppId
export convert, DefsBotId
export convert, DefsChannel
export convert, DefsChannelId
export convert, DefsChannelName
export convert, DefsCommentId
export convert, DefsDmId
export convert, DefsEnterpriseId
export convert, DefsEnterpriseName
export convert, DefsEnterpriseUserId
export convert, DefsFileId
export convert, DefsGroupId
export convert, DefsOkFalse
export convert, DefsOkTrue
export convert, DefsOptionalAppId
export convert, DefsPinnedInfo
export convert, DefsReminderId
export convert, DefsSubteamId
export convert, DefsTeam
export convert, DefsTopicPurposeCreator
export convert, DefsTs
export convert, DefsUserId
export convert, DefsWorkspaceId
export convert, ObjsBotProfile
export convert, ObjsBotProfileIcons
export convert, ObjsChannel
export convert, ObjsChannelPurpose
export convert, ObjsComment
export convert, ObjsComments
export convert, ObjsConversation
export convert, ObjsEnterpriseUser
export convert, ObjsExternalOrgMigrations
export convert, ObjsExternalOrgMigrationsCurrent
export convert, ObjsFile
export convert, ObjsFileShares
export convert, ObjsIcon
export convert, ObjsMessage
export convert, ObjsMessageAttachments
export convert, ObjsMessageIcons
export convert, ObjsPaging
export convert, ObjsPrimaryOwner
export convert, ObjsReaction
export convert, ObjsReminder
export convert, ObjsResources
export convert, ObjsResponseMetadata
export convert, ObjsScopes
export convert, ObjsSubteam
export convert, ObjsSubteamPrefs
export convert, ObjsTeam
export convert, ObjsTeamProfileField
export convert, ObjsTeamProfileFieldOption
export convert, ObjsTeamSsoProvider
export convert, ObjsUser
export convert, ObjsUserProfile
export convert, ObjsUserProfileShort

# export operations
export convert, AdminApi, AdminAppsApi, AdminAppsApprovedApi, AdminAppsRequestsApi, AdminAppsRestrictedApi, AdminConversationsApi, AdminConversationsEkmApi, AdminConversationsRestrictAccessApi, AdminEmojiApi, AdminInviteRequestsApi, AdminInviteRequestsApprovedApi, AdminInviteRequestsDeniedApi, AdminTeamsApi, AdminTeamsAdminsApi, AdminTeamsOwnersApi, AdminTeamsSettingsApi, AdminUsergroupsApi, AdminUsersApi, AdminUsersSessionApi, ApiApi, AppsApi, AppsEventAuthorizationsApi, AppsPermissionsApi, AppsPermissionsResourcesApi, AppsPermissionsScopesApi, AppsPermissionsUsersApi, AuthApi, BotsApi, CallsApi, CallsParticipantsApi, ChatApi, ChatScheduledMessagesApi, ConversationsApi, DialogApi, DndApi, EmojiApi, FilesApi, FilesCommentsApi, FilesRemoteApi, MigrationApi, OauthApi, OauthV2Api, PinsApi, ReactionsApi, RemindersApi, RtmApi, SearchApi, StarsApi, TeamApi, TeamProfileApi, UsergroupsApi, UsergroupsUsersApi, UsersApi, UsersProfileApi, ViewsApi, WorkflowsApi

export check_required, field_name, property_type, hasproperty, propertynames, validate_property, convert

end
